services:
  - type: web
    name: back-app-viajes
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BACKEND_URL
        value: https://back-app-viajes.onrender.com
      - key: KEEP_ALIVE_URL
        value: https://back-app-viajes.onrender.com/ping
      - key: KEEP_ALIVE_INTERVAL_MINUTES
        value: 10
      - key: KEEP_ALIVE_ENABLED
        value: true
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false